// ecosystem.config.js — PM2 进程配置
module.exports = {
  apps: [
    {
      name: 'poker-api',
      script: './server/poker-api/index.js',
      instances: 1,
      autorestart: true,
      max_memory_restart: '200M',
      env: {
        NODE_ENV: 'production',
        POKER_API_PORT: 3000,
        DB_HOST: '127.0.0.1',
        DB_PORT: 5432,
        DB_NAME: 'poker_night',
        DB_USER: 'poker',
        DB_PASSWORD: 'poker123',
        JWT_SECRET: 'poker-night-secret-2026',
      },
    },
    {
      name: 'poker-socket',
      script: './server/poker-socket/index.js',
      instances: 1,
      autorestart: true,
      max_memory_restart: '200M',
      env: {
        NODE_ENV: 'production',
        POKER_SOCKET_PORT: 3001,
        DB_HOST: '127.0.0.1',
        DB_PORT: 5432,
        DB_NAME: 'poker_night',
        DB_USER: 'poker',
        DB_PASSWORD: 'poker123',
        JWT_SECRET: 'poker-night-secret-2026',
      },
    },
    {
      name: 'payment-svc',
      script: './server/payment-svc/index.js',
      instances: 1,
      autorestart: true,
      max_memory_restart: '150M',
      env: {
        NODE_ENV: 'production',
        PAYMENT_PORT: 3002,
        DB_HOST: '127.0.0.1',
        DB_PORT: 5432,
        DB_NAME: 'poker_night',
        DB_USER: 'poker',
        DB_PASSWORD: 'poker123',
        PUBLIC_BASE_URL: 'https://poker.clawclaw.tech',
        PUBLIC_RETURN_URL: 'https://poker.clawclaw.tech',
        // 虎皮椒配置
        XUNHU_API: 'https://api.xunhupay.com/payment/do.html',
        XUNHU_APPID: '201906182246',
        XUNHU_APPKEY: '5995adfd45da21ea5a70c086df023c22',
      },
    },
    {
      name: 'merchant-api',
      script: './server/merchant-api/index.js',
      instances: 1,
      autorestart: true,
      max_memory_restart: '150M',
      env: {
        NODE_ENV: 'production',
        MERCHANT_PORT: 3003,
        DB_HOST: '127.0.0.1',
        DB_PORT: 5432,
        DB_NAME: 'poker_night',
        DB_USER: 'poker',
        DB_PASSWORD: 'poker123',
        JWT_SECRET: 'poker-night-secret-2026',
      },
    },
    {
      name: 'agent-api',
      script: './server/agent-api/index.js',
      instances: 1,
      autorestart: true,
      max_memory_restart: '150M',
      env: {
        NODE_ENV: 'production',
        AGENT_PORT: 3004,
        DB_HOST: '127.0.0.1',
        DB_PORT: 5432,
        DB_NAME: 'poker_night',
        DB_USER: 'poker',
        DB_PASSWORD: 'poker123',
        JWT_SECRET: 'poker-night-secret-2026',
      },
    },
  ],
};
