// ecosystem.config.js — PM2 进程配置
module.exports = {
  apps: [
    {
      name: 'poker-api',
      script: './server/poker-api/index.js',
      instances: 1,
      autorestart: true,
      max_memory_restart: '200M',
      env: {
        NODE_ENV: 'production',
        POKER_API_PORT: 3000,
        DB_HOST: '127.0.0.1',
        DB_PORT: 5432,
        DB_NAME: 'poker_night',
        DB_USER: 'poker',
        DB_PASSWORD: 'poker123',
        JWT_SECRET: 'poker-night-secret-2026',
      },
    },
    {
      name: 'poker-socket',
      script: './server/poker-socket/index.js',
      instances: 1,
      autorestart: true,
      max_memory_restart: '200M',
      env: {
        NODE_ENV: 'production',
        POKER_SOCKET_PORT: 3001,
        DB_HOST: '127.0.0.1',
        DB_PORT: 5432,
        DB_NAME: 'poker_night',
        DB_USER: 'poker',
        DB_PASSWORD: 'poker123',
        JWT_SECRET: 'poker-night-secret-2026',
      },
    },
    {
      name: 'payment-svc',
      script: './server/payment-svc/index.js',
      instances: 1,
      autorestart: true,
      max_memory_restart: '150M',
      env: {
        NODE_ENV: 'production',
        PAYMENT_PORT: 3002,
        DB_HOST: '127.0.0.1',
        DB_PORT: 5432,
        DB_NAME: 'poker_night',
        DB_USER: 'poker',
        DB_PASSWORD: 'poker123',
        PUBLIC_BASE_URL: 'http://43.164.130.145:3002',
        PUBLIC_RETURN_URL: 'http://43.164.130.145',
        // 虎皮椒配置（部署时填入实际值）
        XUNHU_APP_ID: '',
        XUNHU_APP_SECRET: '',
        XUNHU_WX_URL: '',
        XUNHU_ALIPAY_URL: '',
      },
    },
    {
      name: 'merchant-api',
      script: './server/merchant-api/index.js',
      instances: 1,
      autorestart: true,
      max_memory_restart: '150M',
      env: {
        NODE_ENV: 'production',
        MERCHANT_PORT: 3003,
        DB_HOST: '127.0.0.1',
        DB_PORT: 5432,
        DB_NAME: 'poker_night',
        DB_USER: 'poker',
        DB_PASSWORD: 'poker123',
        JWT_SECRET: 'poker-night-secret-2026',
      },
    },
  ],
};
